/* Auto-generated by scripts/refresh.mjs - do not edit by hand */
window.SEO_DATA = {
  pulled: "6 Jul 2026",
  overview: { keywords: 528, traffic: 1456, authority: 18, backlinks: 769, refdomains: 249, trustScore: 18, follows: 539, nofollows: 228, referringIPs: 218 },
  organicHistory: [
    ["Jul 24",686,1608],["Aug 24",644,1816],["Sep 24",715,1859],["Oct 24",686,1860],["Nov 24",692,1845],["Dec 24",626,2082],
    ["Jan 25",487,1624],["Feb 25",486,1616],["Mar 25",520,1920],["Apr 25",551,1636],["May 25",575,1012],["Jun 25",635,2082],
    ["Jul 25",632,1412],["Aug 25",674,1817],["Sep 25",692,1193],["Oct 25",695,1100],["Nov 25",642,1110],["Dec 25",604,1204],
    ["Jan 26",672,1244],["Feb 26",738,1678],["Mar 26",657,1584],["Apr 26",571,1513],["May 26",588,1561],["Jun 26",541,1450]
  ],
  linkHistory: [
    ["Aug 24",12839,1784],["Sep 24",11669,1627],["Oct 24",9798,1443],["Nov 24",8137,1275],["Dec 24",6705,1152],
    ["Jan 25",5086,987],["Feb 25",3634,809],["Mar 25",2522,600],["Apr 25",2229,546],["May 25",1988,515],["Jun 25",1593,449],
    ["Jul 25",1332,400],["Aug 25",982,363],["Sep 25",663,310],["Oct 25",511,268],["Nov 25",439,240],["Dec 25",416,223],
    ["Jan 26",408,224],["Feb 26",388,185],["Mar 26",417,194],["Apr 26",518,219],["May 26",611,236],["Jun 26",741,248],["Jul 26",769,249]
  ],
  topKeywords: [
    ["cascamite",1,0,390,6.6,"/products/cascamite-powdered-resin-one-shot-wood-glue/"],
    ["cascamite glue",1,0,480,4.3,"/products/cascamite-powdered-resin-one-shot-wood-glue/"],
    ["epoxy adhesive glue",1,0,590,2.6,"/adhesive-type/epoxy-adhesive/"],
    ["epoxy adhesive",2,0,880,2.6,"/adhesive-type/epoxy-adhesive/"],
    ["artificial grass tools",1,0,260,2.3,"/equipment/artificial-grass-tools/"],
    ["cascamite wood glue",1,0,260,2.3,"/products/cascamite-powdered-resin-one-shot-wood-glue/"],
    ["epoxy resin adhesive glue",2,0,880,2.1,"/adhesive-type/epoxy-adhesive/"],
    ["strongest wood glue",4,0,880,1.4,"/x-to-y-comparisons/what-is-the-strongest-wood-glue-expert-guide/"],
    ["epoxy resin adhesive",3,0,720,1.4,"/adhesive-type/epoxy-adhesive/"],
    ["d3 wood glue",1,0,140,1.2,"/how-to-advice/what-is-the-difference-between-d1-d2-d3-and-d4-wood-adhesives/"],
    ["best grab adhesive",5,0,590,1.2,"/how-to-advice/best-grab-adhesive/"],
    ["glue pu",8,0,2400,1.1,"/video-tutorials/what-is-the-strongest-waterproof-expanding-wood-glue-pu-gel/"],
    ["loctite 406",5,0,590,1.0,"/products/loctite-406-superglue-cyanoacrylate-20g/"],
    ["strong wood glue",4,3,720,0.9,"/x-to-y-comparisons/what-is-the-strongest-wood-glue-expert-guide/"],
    ["best wood glue",7,0,880,0.8,"/x-to-y-comparisons/what-is-the-strongest-wood-glue-expert-guide/"],
    ["synthetic turf joining tape",1,0,390,0.8,"/products/turfstikk-st500-artificial-grass-joining-seam-tape/"],
    ["urea formaldehyde",7,0,1000,0.5,"/adhesive-type/urea-formaldehyde/"]
  ],
  gained: [
    ["epoxy resin glue",23,"–",1300],
    ["super glue activator",32,"–",880],
    ["strong wood glue",4,7,720],
    ["hot melt adhesive",27,"–",320],
    ["stikatak",35,"–",170],
    ["best aluminum to aluminum adhesive",11,"–",110],
    ["glue spatula",17,"–",110]
  ],
  lost: [
    ["5278 (Prefere hardener)","out",5,590],
    ["covers timber and builders merchants chichester","out",35,480],
    ["pva woodworking glue","out",31,480],
    ["bondaro","out",80,210],
    ["spray glue activator",30,29,110]
  ],
  pages: [
    ["/products/cascamite-powdered-resin-one-shot-wood-glue/",12,263,18.1],
    ["/x-to-y-comparisons/need-to-stick-artificial-grass-to-concrete.../",19,169,11.6],
    ["/ (homepage)",8,142,9.8],
    ["/adhesive-type/epoxy-adhesive/",23,141,9.7],
    ["/how-to-advice/what-is-the-difference-between-d1-d2-d3-and-d4.../",17,133,9.1],
    ["/x-to-y-comparisons/what-is-the-strongest-wood-glue-expert-guide/",18,78,5.4],
    ["/products/turfstikk-st500-artificial-grass-joining-seam-tape/",24,71,4.9],
    ["/equipment/artificial-grass-tools/",7,65,4.5],
    ["/adhesive-type/urea-formaldehyde/",11,55,3.8],
    ["/how-to-advice/what-is-the-best-and-strongest-d4-pva-wood-glue.../",4,45,3.1],
    ["/adhesive-type/polyurethane-adhesive/",22,23,1.6]
  ],
  refdomains: [
    ["wikipedia.org",100,1],["bing.com",97,9],["yell.com",72,1],["grokipedia.com",62,5],
    ["pocketmags.com",47,2],["pabbly.com",44,1],["neverbounce.com",43,1],["boatdesign.net",34,1],
    ["externalworksindex.co.uk",33,9],["plastiks.io",33,3],["brettmartin.com",32,1],["bwf.org.uk",32,1]
  ],
  tasks: [
    {id:"t1",p:"high",title:"Push 'epoxy resin glue' from p23 to page 1",body:"Biggest new opportunity: 1,300 searches/mo and the epoxy page already holds positions 1 to 3 for four sister terms. Add the exact phrase to the H1 area, intro and product copy on /adhesive-type/epoxy-adhesive/, and point 3 to 4 internal links at it with that anchor.",chips:["1,300/mo","p23 → p1-10","epoxy-adhesive"]},
    {id:"t2",p:"high",title:"Rebuild the PVA wood glue category page",body:"'pva woodworking glue' (480/mo) dropped out of the top 100 entirely. The D1-D4 advice article ranks no.1 for 'd3 wood glue', so link from it into /adhesive-type/pva-wood-glue/ and rewrite the category page with proper D3/D4 selection guidance.",chips:["480/mo","lost from top 100","pva-wood-glue"]},
    {id:"t3",p:"high",title:"Keep the referring domain rebuild going",body:"Domains bottomed at 185 in Feb, now 249 and climbing five months straight. Next wave: BWF member listing is live, so chase FIRA, TTF and builders merchant stockist pages, plus brand backlinks from Beardow Adams and Forgeway distributor pages.",chips:["185 → 249","AS 18","directories + brands"]},
    {id:"t4",p:"med",title:"Fix the Prefere 5278 product page",body:"'5278' (590/mo) dropped from p5 to out of the index. Check the product page is live, in stock and indexable; if the product was discontinued, 301 it to the nearest Prefere alternative rather than losing the equity.",chips:["590/mo","was p5","prefere-5278"]},
    {id:"t5",p:"med",title:"Expand the glue activator page",body:"'super glue activator' (880/mo) just entered at p32 while 'spray glue activator' slipped to p30. One decent rewrite of /adhesive-type/glue-activator/ covering both terms plus aerosol vs pump formats should lift the pair together.",chips:["880/mo","p32 new","glue-activator"]},
    {id:"t6",p:"med",title:"Finish the aluminium adhesive rewrite",body:"'best aluminum to aluminum adhesive' entered at p11, one spot off page 1. The in-progress rewrite should cover both UK and US spellings and add a comparison table; a couple of internal links from the epoxy and metal-bonding pages will close the gap.",chips:["110/mo","p11 → p10","metal-to-metal"]},
    {id:"t7",p:"low",title:"Optimise the hot melt adhesive category",body:"'hot melt adhesive' entered at p27 (320/mo, low competition at 0.66). Freshen the category copy, add Beardow Adams product depth and FAQ schema.",chips:["320/mo","p27 new","hot-melt"]},
    {id:"t8",p:"low",title:"Check store locator indexation",body:"The Covers Chichester store page (480/mo for the branded merchant term) fell out of the top 100. Audit the /store-location/ template for thin content or noindex issues; these pages earn merchant-intent traffic cheaply.",chips:["480/mo","store-location","technical"]}
  ]
};
